spring.application.name=demo
# Configuración de la conexión a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/gestor_psicologico?useSSL=false&serverTimezone=America/Mazatlan
spring.datasource.username=root
spring.datasource.password=Upsin-068322
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate (El ORM que mapeará nuestras tablas)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jackson.time-zone=America/Mazatlan

springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.operationsSorter=alpha