spring.application.name=demo
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.sql.init.separator=$$
server.port=${PORT:8080}

# AQUI ESTA LA MAGIA: Agregamos allowPublicKeyRetrieval=true
spring.datasource.url=jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQLDATABASE:gestor_psicologico}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Mazatlan

spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:Upsin-068322}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuracion de Hibernate (ORM)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jackson.time-zone=America/Mazatlan

springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.operationsSorter=alpha
server.forward-headers-strategy=framework