spring.application.name=demo
# Configuración de la conexión a MySQL
server.port=${PORT:8080}
spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/gestor_psicologico?useSSL=false&serverTimezone=America/Mazatlan}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:Upsin-068322}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate (El ORM que mapeará nuestras tablas)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jackson.time-zone=America/Mazatlan

springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.operationsSorter=alpha